/**
 * Pause Customizer Module Constants
 */

export const MODULE_ID = 'pause-customizer';

/** Settings keys */
export const SETTINGS = {
  CHOOSE_FILE: 'chooseFile',
  OPACITY: 'opacity',
  PAUSE_TEXT: 'pauseText',
  PAUSE_TEXT_FONT_FAMILY: 'pauseTextFontFamily',
  PAUSE_TEXT_COLOR: 'pauseTextColor',
  PAUSE_TEXT_FONT_SIZE: 'pauseTextFontSize',
  PAUSE_TEXT_SHADOW: 'pauseTextShadow',
  ANIMATION_DIRECTION: 'animationDirection',
  ANIMATION_DURATION: 'animationDuration',
  ANIMATION_TIMING: 'animationTiming',
  PAUSE_BACKGROUND: 'pauseBackground',
} as const;

/** I18n keys */
export const I18N_KEYS = {
  SELECT_IMAGE: 'PAUSE_CUSTOMIZER.SELECT_IMAGE',
  SELECT_IMAGE_HINT: 'PAUSE_CUSTOMIZER.SELECT_IMAGE_HINT',
  OPACITY: 'PAUSE_CUSTOMIZER.OPACITY',
  OPACITY_HINT: 'PAUSE_CUSTOMIZER.OPACITY_HINT',
  PAUSE_TEXT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT',
  PAUSE_TEXT_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_HINT',
  PAUSE_TEXT_FONT_FAMILY: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_FONT_FAMILY',
  PAUSE_TEXT_FONT_FAMILY_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_FONT_FAMILY_HINT',
  PAUSE_TEXT_COLOR: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_COLOR',
  PAUSE_TEXT_COLOR_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_COLOR_HINT',
  PAUSE_TEXT_FONT_SIZE: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_FONT_SIZE',
  PAUSE_TEXT_FONT_SIZE_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_FONT_SIZE_HINT',
  PAUSE_TEXT_SHADOW: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_SHADOW',
  PAUSE_TEXT_SHADOW_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_SHADOW_HINT',
  ANIMATION_DIRECTION: 'PAUSE_CUSTOMIZER.ANIMATION_DIRECTION',
  ANIMATION_DIRECTION_HINT: 'PAUSE_CUSTOMIZER.ANIMATION_DIRECTION_HINT',
  ANIMATION_DURATION: 'PAUSE_CUSTOMIZER.ANIMATION_DURATION',
  ANIMATION_DURATION_HINT: 'PAUSE_CUSTOMIZER.ANIMATION_DURATION_HINT',
  ANIMATION_TIMING: 'PAUSE_CUSTOMIZER.ANIMATION_TIMING',
  ANIMATION_TIMING_HINT: 'PAUSE_CUSTOMIZER.ANIMATION_TIMING_HINT',
  PAUSE_BACKGROUND: 'PAUSE_CUSTOMIZER.PAUSE_BACKGROUND',
  PAUSE_BACKGROUND_HINT: 'PAUSE_CUSTOMIZER.PAUSE_BACKGROUND_HINT',
  DEFAULT: 'PAUSE_CUSTOMIZER.DEFAULT',
} as const;
