/**
 * Pause Customizer Module Constants
 */

export const MODULE_ID = 'pause-customizer';

/** Settings keys */
export const SETTINGS = {
  CHOOSE_FILE: 'chooseFile',
  IMAGE_WIDTH: 'imageWidth',
  IMAGE_HEIGHT: 'imageHeight',
  OPACITY: 'opacity',
  PAUSE_TEXT: 'pauseText',
  PAUSE_TEXT_FONT_FAMILY: 'pauseTextFontFamily',
  PAUSE_TEXT_COLOR: 'pauseTextColor',
  PAUSE_TEXT_FONT_SIZE: 'pauseTextFontSize',
  PAUSE_TEXT_FONT_WEIGHT: 'pauseTextFontWeight',
  PAUSE_TEXT_TRANSFORM: 'pauseTextTransform',
  PAUSE_TEXT_LETTER_SPACING: 'pauseTextLetterSpacing',
  PAUSE_TEXT_SHADOW: 'pauseTextShadow',
  ANIMATION_DIRECTION: 'animationDirection',
  ANIMATION_DURATION: 'animationDuration',
  ANIMATION_TIMING: 'animationTiming',
  IMAGE_MARGIN_TOP: 'imageMarginTop',
  PAUSE_TEXT_MARGIN_TOP: 'pauseTextMarginTop',
  PAUSE_BACKGROUND: 'pauseBackground',
  PAUSE_BACKGROUND_IMAGE: 'pauseBackgroundImage',
} as const;

/**
 * Foundry v14 default values for the pause overlay.
 * Sourced from GamePause._prepareContext() and #pause CSS rules.
 * Used as static fallback when dynamic reading is not possible.
 */
export const DEFAULTS: Record<string, string> = {
  chooseFile: 'ui/pause.svg',
  imageWidth: '',
  imageHeight: '',
  opacity: '1',
  pauseText: '',
  pauseTextFontFamily: 'default',
  pauseTextColor: '#ada7b8',
  pauseTextFontSize: '',
  pauseTextFontWeight: 'default',
  pauseTextTransform: 'default',
  pauseTextLetterSpacing: '',
  pauseTextShadow: '',
  animationDirection: 'default',
  animationDuration: '5s',
  animationTiming: 'default',
  imageMarginTop: '',
  pauseTextMarginTop: '',
  pauseBackground: '',
  pauseBackgroundImage: '',
};

/** I18n keys */
export const I18N_KEYS = {
  SELECT_IMAGE: 'PAUSE_CUSTOMIZER.SELECT_IMAGE',
  SELECT_IMAGE_HINT: 'PAUSE_CUSTOMIZER.SELECT_IMAGE_HINT',
  BROWSE_FILES: 'PAUSE_CUSTOMIZER.BROWSE_FILES',
  BROWSE_FOLDER: 'PAUSE_CUSTOMIZER.BROWSE_FOLDER',
  IMAGE_WIDTH: 'PAUSE_CUSTOMIZER.IMAGE_WIDTH',
  IMAGE_WIDTH_HINT: 'PAUSE_CUSTOMIZER.IMAGE_WIDTH_HINT',
  IMAGE_HEIGHT: 'PAUSE_CUSTOMIZER.IMAGE_HEIGHT',
  IMAGE_HEIGHT_HINT: 'PAUSE_CUSTOMIZER.IMAGE_HEIGHT_HINT',
  OPACITY: 'PAUSE_CUSTOMIZER.OPACITY',
  OPACITY_HINT: 'PAUSE_CUSTOMIZER.OPACITY_HINT',
  PAUSE_TEXT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT',
  PAUSE_TEXT_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_HINT',
  PAUSE_TEXT_FONT_FAMILY: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_FONT_FAMILY',
  PAUSE_TEXT_FONT_FAMILY_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_FONT_FAMILY_HINT',
  PAUSE_TEXT_COLOR: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_COLOR',
  PAUSE_TEXT_COLOR_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_COLOR_HINT',
  PAUSE_TEXT_FONT_SIZE: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_FONT_SIZE',
  PAUSE_TEXT_FONT_SIZE_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_FONT_SIZE_HINT',
  PAUSE_TEXT_FONT_WEIGHT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_FONT_WEIGHT',
  PAUSE_TEXT_FONT_WEIGHT_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_FONT_WEIGHT_HINT',
  PAUSE_TEXT_TRANSFORM: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_TRANSFORM',
  PAUSE_TEXT_TRANSFORM_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_TRANSFORM_HINT',
  PAUSE_TEXT_LETTER_SPACING: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_LETTER_SPACING',
  PAUSE_TEXT_LETTER_SPACING_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_LETTER_SPACING_HINT',
  PAUSE_TEXT_SHADOW: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_SHADOW',
  PAUSE_TEXT_SHADOW_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_SHADOW_HINT',
  ANIMATION_DIRECTION: 'PAUSE_CUSTOMIZER.ANIMATION_DIRECTION',
  ANIMATION_DIRECTION_HINT: 'PAUSE_CUSTOMIZER.ANIMATION_DIRECTION_HINT',
  ANIMATION_DURATION: 'PAUSE_CUSTOMIZER.ANIMATION_DURATION',
  ANIMATION_DURATION_HINT: 'PAUSE_CUSTOMIZER.ANIMATION_DURATION_HINT',
  ANIMATION_TIMING: 'PAUSE_CUSTOMIZER.ANIMATION_TIMING',
  ANIMATION_TIMING_HINT: 'PAUSE_CUSTOMIZER.ANIMATION_TIMING_HINT',
  IMAGE_MARGIN_TOP: 'PAUSE_CUSTOMIZER.IMAGE_MARGIN_TOP',
  IMAGE_MARGIN_TOP_HINT: 'PAUSE_CUSTOMIZER.IMAGE_MARGIN_TOP_HINT',
  PAUSE_TEXT_MARGIN_TOP: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_MARGIN_TOP',
  PAUSE_TEXT_MARGIN_TOP_HINT: 'PAUSE_CUSTOMIZER.PAUSE_TEXT_MARGIN_TOP_HINT',
  PAUSE_BACKGROUND: 'PAUSE_CUSTOMIZER.PAUSE_BACKGROUND',
  PAUSE_BACKGROUND_HINT: 'PAUSE_CUSTOMIZER.PAUSE_BACKGROUND_HINT',
  PAUSE_BACKGROUND_IMAGE: 'PAUSE_CUSTOMIZER.PAUSE_BACKGROUND_IMAGE',
  PAUSE_BACKGROUND_IMAGE_HINT: 'PAUSE_CUSTOMIZER.PAUSE_BACKGROUND_IMAGE_HINT',
  DEFAULT: 'PAUSE_CUSTOMIZER.DEFAULT',
  NONE: 'PAUSE_CUSTOMIZER.NONE',
  DIRECTION_ROTATE: 'PAUSE_CUSTOMIZER.DIRECTION_ROTATE',
  DIRECTION_ROTATE_REVERSE: 'PAUSE_CUSTOMIZER.DIRECTION_ROTATE_REVERSE',
  DIRECTION_ALTERNATE: 'PAUSE_CUSTOMIZER.DIRECTION_ALTERNATE',
  DIRECTION_ALTERNATE_REVERSE: 'PAUSE_CUSTOMIZER.DIRECTION_ALTERNATE_REVERSE',
  RESET_DEFAULTS: 'PAUSE_CUSTOMIZER.RESET_DEFAULTS',
  RESET_DEFAULTS_DONE: 'PAUSE_CUSTOMIZER.RESET_DEFAULTS_DONE',
} as const;
